### PR TITLE
Fix issue #2: change Java::OrgJruby::RubyTime object into Time object

### PR DESCRIPTION
**Pull request by jca02266**
This is a workaround for Issue #2

### CODE REVIEW

**Comment by jca02266** [comment]
This is because embulk pass the Java::OrgJruby::RubyTime object.

https://github.com/embulk/embulk/blob/9ab3c94/embulk-core/src/main/ruby/embulk/schema.rb#L39

**Comment by jca02266** [comment]
Reported to embulk project.

https://github.com/embulk/embulk/issues/970

**Comment by jca02266** [comment]
Embulk was fixed by following PR.
https://github.com/embulk/embulk/pull/971

This PR uses for workaround for embulk 0.9.3 or earlier.

**Comment by joker1007** [comment]
Thanks!

**Pull request closed without merging**
